//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLOG_Model.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Y2018AP51BLOGEntities : DbContext
    {
        public Y2018AP51BLOGEntities()
            : base("name=Y2018AP51BLOGEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Blog> tbl_Blog { get; set; }
        public virtual DbSet<tbl_Users> tbl_Users { get; set; }
        public virtual DbSet<tbl_Contact> tbl_Contact { get; set; }
    
        public virtual int SP_Blog_create(Nullable<System.Guid> idBlog, string title, string summury, string contents, string author, Nullable<System.Guid> idUser, Nullable<System.DateTime> created_at, Nullable<System.DateTime> updated_at, Nullable<bool> isDel)
        {
            var idBlogParameter = idBlog.HasValue ?
                new ObjectParameter("idBlog", idBlog) :
                new ObjectParameter("idBlog", typeof(System.Guid));
    
            var titleParameter = title != null ?
                new ObjectParameter("title", title) :
                new ObjectParameter("title", typeof(string));
    
            var summuryParameter = summury != null ?
                new ObjectParameter("summury", summury) :
                new ObjectParameter("summury", typeof(string));
    
            var contentsParameter = contents != null ?
                new ObjectParameter("contents", contents) :
                new ObjectParameter("contents", typeof(string));
    
            var authorParameter = author != null ?
                new ObjectParameter("author", author) :
                new ObjectParameter("author", typeof(string));
    
            var idUserParameter = idUser.HasValue ?
                new ObjectParameter("idUser", idUser) :
                new ObjectParameter("idUser", typeof(System.Guid));
    
            var created_atParameter = created_at.HasValue ?
                new ObjectParameter("created_at", created_at) :
                new ObjectParameter("created_at", typeof(System.DateTime));
    
            var updated_atParameter = updated_at.HasValue ?
                new ObjectParameter("updated_at", updated_at) :
                new ObjectParameter("updated_at", typeof(System.DateTime));
    
            var isDelParameter = isDel.HasValue ?
                new ObjectParameter("isDel", isDel) :
                new ObjectParameter("isDel", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Blog_create", idBlogParameter, titleParameter, summuryParameter, contentsParameter, authorParameter, idUserParameter, created_atParameter, updated_atParameter, isDelParameter);
        }
    
        public virtual int SP_Blog_delete(Nullable<System.Guid> idBlog)
        {
            var idBlogParameter = idBlog.HasValue ?
                new ObjectParameter("idBlog", idBlog) :
                new ObjectParameter("idBlog", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Blog_delete", idBlogParameter);
        }
    
        public virtual ObjectResult<SP_Blog_getElementById_Result> SP_Blog_getElementById(Nullable<System.Guid> idBlog)
        {
            var idBlogParameter = idBlog.HasValue ?
                new ObjectParameter("idBlog", idBlog) :
                new ObjectParameter("idBlog", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Blog_getElementById_Result>("SP_Blog_getElementById", idBlogParameter);
        }
    
        public virtual ObjectResult<SP_Blog_getElements_Result> SP_Blog_getElements()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Blog_getElements_Result>("SP_Blog_getElements");
        }
    
        public virtual int SP_Blog_update(Nullable<System.Guid> idBlog, string title, string summury, string contents, string author, Nullable<System.Guid> idUser, Nullable<System.DateTime> created_at, Nullable<System.DateTime> updated_at, Nullable<bool> isDel)
        {
            var idBlogParameter = idBlog.HasValue ?
                new ObjectParameter("idBlog", idBlog) :
                new ObjectParameter("idBlog", typeof(System.Guid));
    
            var titleParameter = title != null ?
                new ObjectParameter("title", title) :
                new ObjectParameter("title", typeof(string));
    
            var summuryParameter = summury != null ?
                new ObjectParameter("summury", summury) :
                new ObjectParameter("summury", typeof(string));
    
            var contentsParameter = contents != null ?
                new ObjectParameter("contents", contents) :
                new ObjectParameter("contents", typeof(string));
    
            var authorParameter = author != null ?
                new ObjectParameter("author", author) :
                new ObjectParameter("author", typeof(string));
    
            var idUserParameter = idUser.HasValue ?
                new ObjectParameter("idUser", idUser) :
                new ObjectParameter("idUser", typeof(System.Guid));
    
            var created_atParameter = created_at.HasValue ?
                new ObjectParameter("created_at", created_at) :
                new ObjectParameter("created_at", typeof(System.DateTime));
    
            var updated_atParameter = updated_at.HasValue ?
                new ObjectParameter("updated_at", updated_at) :
                new ObjectParameter("updated_at", typeof(System.DateTime));
    
            var isDelParameter = isDel.HasValue ?
                new ObjectParameter("isDel", isDel) :
                new ObjectParameter("isDel", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Blog_update", idBlogParameter, titleParameter, summuryParameter, contentsParameter, authorParameter, idUserParameter, created_atParameter, updated_atParameter, isDelParameter);
        }
    
        public virtual int SP_User_create(Nullable<System.Guid> idUser, string userName, string passWord, string email, string fullName, string mobile, Nullable<System.DateTime> created_at, Nullable<System.DateTime> updated_at, Nullable<bool> isDel)
        {
            var idUserParameter = idUser.HasValue ?
                new ObjectParameter("idUser", idUser) :
                new ObjectParameter("idUser", typeof(System.Guid));
    
            var userNameParameter = userName != null ?
                new ObjectParameter("userName", userName) :
                new ObjectParameter("userName", typeof(string));
    
            var passWordParameter = passWord != null ?
                new ObjectParameter("passWord", passWord) :
                new ObjectParameter("passWord", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var fullNameParameter = fullName != null ?
                new ObjectParameter("fullName", fullName) :
                new ObjectParameter("fullName", typeof(string));
    
            var mobileParameter = mobile != null ?
                new ObjectParameter("mobile", mobile) :
                new ObjectParameter("mobile", typeof(string));
    
            var created_atParameter = created_at.HasValue ?
                new ObjectParameter("created_at", created_at) :
                new ObjectParameter("created_at", typeof(System.DateTime));
    
            var updated_atParameter = updated_at.HasValue ?
                new ObjectParameter("updated_at", updated_at) :
                new ObjectParameter("updated_at", typeof(System.DateTime));
    
            var isDelParameter = isDel.HasValue ?
                new ObjectParameter("isDel", isDel) :
                new ObjectParameter("isDel", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_User_create", idUserParameter, userNameParameter, passWordParameter, emailParameter, fullNameParameter, mobileParameter, created_atParameter, updated_atParameter, isDelParameter);
        }
    
        public virtual int SP_User_delete(Nullable<System.Guid> idUser)
        {
            var idUserParameter = idUser.HasValue ?
                new ObjectParameter("idUser", idUser) :
                new ObjectParameter("idUser", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_User_delete", idUserParameter);
        }
    
        public virtual ObjectResult<SP_User_getElementById_Result> SP_User_getElementById(Nullable<System.Guid> idUser)
        {
            var idUserParameter = idUser.HasValue ?
                new ObjectParameter("idUser", idUser) :
                new ObjectParameter("idUser", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_User_getElementById_Result>("SP_User_getElementById", idUserParameter);
        }
    
        public virtual ObjectResult<SP_User_getElements_Result> SP_User_getElements()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_User_getElements_Result>("SP_User_getElements");
        }
    
        public virtual int SP_User_update(Nullable<System.Guid> idUser, string userName, string passWord, string email, string fullName, string mobile, Nullable<System.DateTime> created_at, Nullable<System.DateTime> updated_at, Nullable<bool> isDel)
        {
            var idUserParameter = idUser.HasValue ?
                new ObjectParameter("idUser", idUser) :
                new ObjectParameter("idUser", typeof(System.Guid));
    
            var userNameParameter = userName != null ?
                new ObjectParameter("userName", userName) :
                new ObjectParameter("userName", typeof(string));
    
            var passWordParameter = passWord != null ?
                new ObjectParameter("passWord", passWord) :
                new ObjectParameter("passWord", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var fullNameParameter = fullName != null ?
                new ObjectParameter("fullName", fullName) :
                new ObjectParameter("fullName", typeof(string));
    
            var mobileParameter = mobile != null ?
                new ObjectParameter("mobile", mobile) :
                new ObjectParameter("mobile", typeof(string));
    
            var created_atParameter = created_at.HasValue ?
                new ObjectParameter("created_at", created_at) :
                new ObjectParameter("created_at", typeof(System.DateTime));
    
            var updated_atParameter = updated_at.HasValue ?
                new ObjectParameter("updated_at", updated_at) :
                new ObjectParameter("updated_at", typeof(System.DateTime));
    
            var isDelParameter = isDel.HasValue ?
                new ObjectParameter("isDel", isDel) :
                new ObjectParameter("isDel", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_User_update", idUserParameter, userNameParameter, passWordParameter, emailParameter, fullNameParameter, mobileParameter, created_atParameter, updated_atParameter, isDelParameter);
        }
    
        public virtual ObjectResult<SP_User_checkLogin_Result> SP_User_checkLogin(string userName, string passWord)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("userName", userName) :
                new ObjectParameter("userName", typeof(string));
    
            var passWordParameter = passWord != null ?
                new ObjectParameter("passWord", passWord) :
                new ObjectParameter("passWord", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_User_checkLogin_Result>("SP_User_checkLogin", userNameParameter, passWordParameter);
        }
    
        public virtual ObjectResult<SP_Blog_getdeletedElements_Result> SP_Blog_getdeletedElements()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Blog_getdeletedElements_Result>("SP_Blog_getdeletedElements");
        }
    
        public virtual ObjectResult<SP_User_getdeletedElements_Result> SP_User_getdeletedElements()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_User_getdeletedElements_Result>("SP_User_getdeletedElements");
        }
    
        public virtual int SP_Blog_deletePermanently(Nullable<System.Guid> idBlog)
        {
            var idBlogParameter = idBlog.HasValue ?
                new ObjectParameter("idBlog", idBlog) :
                new ObjectParameter("idBlog", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Blog_deletePermanently", idBlogParameter);
        }
    
        public virtual int SP_User_deletePermanently(Nullable<System.Guid> idUser)
        {
            var idUserParameter = idUser.HasValue ?
                new ObjectParameter("idUser", idUser) :
                new ObjectParameter("idUser", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_User_deletePermanently", idUserParameter);
        }
    
        public virtual int SP_Blog_restore(Nullable<System.Guid> idBlog)
        {
            var idBlogParameter = idBlog.HasValue ?
                new ObjectParameter("idBlog", idBlog) :
                new ObjectParameter("idBlog", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Blog_restore", idBlogParameter);
        }
    
        public virtual int SP_User_restore(Nullable<System.Guid> idUser)
        {
            var idUserParameter = idUser.HasValue ?
                new ObjectParameter("idUser", idUser) :
                new ObjectParameter("idUser", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_User_restore", idUserParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_User_getNumberUser()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_User_getNumberUser");
        }
    
        public virtual ObjectResult<SP_User_getPaging_Result> SP_User_getPaging(Nullable<int> start, Nullable<int> length)
        {
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(int));
    
            var lengthParameter = length.HasValue ?
                new ObjectParameter("length", length) :
                new ObjectParameter("length", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_User_getPaging_Result>("SP_User_getPaging", startParameter, lengthParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_Blog_getNumberBlog()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_Blog_getNumberBlog");
        }
    
        public virtual ObjectResult<SP_Blog_getPaging_Result> SP_Blog_getPaging(Nullable<int> start, Nullable<int> length)
        {
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(int));
    
            var lengthParameter = length.HasValue ?
                new ObjectParameter("length", length) :
                new ObjectParameter("length", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Blog_getPaging_Result>("SP_Blog_getPaging", startParameter, lengthParameter);
        }
    
        public virtual ObjectResult<SP_User_Search_Result> SP_User_Search(string key)
        {
            var keyParameter = key != null ?
                new ObjectParameter("key", key) :
                new ObjectParameter("key", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_User_Search_Result>("SP_User_Search", keyParameter);
        }
    
        public virtual ObjectResult<SP_User_Search_Paging_Result> SP_User_Search_Paging(string key, Nullable<int> start, Nullable<int> length)
        {
            var keyParameter = key != null ?
                new ObjectParameter("key", key) :
                new ObjectParameter("key", typeof(string));
    
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(int));
    
            var lengthParameter = length.HasValue ?
                new ObjectParameter("length", length) :
                new ObjectParameter("length", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_User_Search_Paging_Result>("SP_User_Search_Paging", keyParameter, startParameter, lengthParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_User_countPaging(string key)
        {
            var keyParameter = key != null ?
                new ObjectParameter("key", key) :
                new ObjectParameter("key", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_User_countPaging", keyParameter);
        }
    
        public virtual int SP_Contact_Insert(Nullable<System.Guid> idContact, string name, string email, Nullable<int> mobile, string message, Nullable<System.DateTime> created_at)
        {
            var idContactParameter = idContact.HasValue ?
                new ObjectParameter("idContact", idContact) :
                new ObjectParameter("idContact", typeof(System.Guid));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var mobileParameter = mobile.HasValue ?
                new ObjectParameter("mobile", mobile) :
                new ObjectParameter("mobile", typeof(int));
    
            var messageParameter = message != null ?
                new ObjectParameter("message", message) :
                new ObjectParameter("message", typeof(string));
    
            var created_atParameter = created_at.HasValue ?
                new ObjectParameter("created_at", created_at) :
                new ObjectParameter("created_at", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Contact_Insert", idContactParameter, nameParameter, emailParameter, mobileParameter, messageParameter, created_atParameter);
        }
    }
}
