//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLOG_Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Contact
    {
        public string Name { get; set; }
        public string Email { get; set; }
        public int Mobile { get; set; }
        public string Message { get; set; }
        public System.DateTime Created_at { get; set; }
        public System.Guid idName { get; set; }
    }
}
